# Generated by Django 4.0 on 2022-04-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='email',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
