# Generated by Django 4.0 on 2022-04-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0005_tag_flower_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
