# Generated by Django 4.0.3 on 2022-05-12 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0008_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
